### PR TITLE
Upgrade dependencies.  Waiting for data-coordinator commit before it can...

### PR DESCRIPTION
**Pull request by chitang**
... build.

### CODE REVIEW

**Comment by velvia** [comment]
LGTM.

**Comment by sokrahta** [comment]
test coverage is 43% ... otherwise
LGTM

**Comment by chitang** [comment]
Increase test coverage will be a different task.  This is for json v3 dependency upgrade.

**Comment by sokrahta** [comment]
thanks @chitang - I would merge anyway, to get you unblocked.

**Pull request merged**
